spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USR:urusso}
    password: ${DATASOURCE_PWD:urussopwd}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
    hikari:
      maximum-pool-size: 5
      schema: vgc
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
    contexts: dev
    drop-first: false
    default-schema: vgc

springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

swagger:
  version: 1.0
  title: VGC Team Wars
  description: Swagger for the VGC Team Wars application

management:
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:359191e2639870f59be5c9dfb67ba23209c4c1ea0ad5140cd8bfd9fba6448184}
    expiration-time: ${JWT_EXPIRATION_TIME:12h}
  refresh:
    secret-key: ${REFRESH_JWT_SECRET_KEY:cc02dc955e61d30ea8e328f72a7a0c2d7d96d5f7a27fa83d0bf9f3da74c144d8}
    expiration-time: ${REFRESH_JWT_EXPIRATION_TIME:30d}

cache:
  jwt-ttl: 12 #hours
  refresh-jwt-ttl: 30 #days